# CloudFormation Template para desplegar en AWS
AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template para Microservicio Simple en ECS Fargate'

Parameters:
  ServiceName:
    Type: String
    Default: microservicio-simple
    Description: Nombre del servicio
  
  DesiredCount:
    Type: Number
    Default: 2
    Description: Número de tareas deseadas

Resources:
  # VPC (usar default si existe)
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group para microservicio
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5000
          ToPort: 5000
          CidrIp: 0.0.0.0/0

  # CloudWatch Log Group
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/ecs/${ServiceName}'
      RetentionInDays: 7

  # IAM Role para ECS Task
  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  # ECR Repository
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref ServiceName
      ImageScanningConfiguration:
        ScanOnPush: true

  # ECS Task Definition
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Ref ServiceName
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: '256'
      Memory: '512'
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      ContainerDefinitions:
        - Name: !Ref ServiceName
          Image: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ECRRepository}:latest'
          PortMappings:
            - ContainerPort: 5000
          Environment:
            - Name: SERVICE_NAME
              Value: !Ref ServiceName
            - Name: ENVIRONMENT
              Value: production
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs

Outputs:
  ECRRepositoryUri:
    Description: URI del repositorio ECR
    Value: !GetAtt ECRRepository.RepositoryUri
  
  LogGroupName:
    Description: Nombre del CloudWatch Log Group
    Value: !Ref LogGroup
