steps:
  # Paso 1: Construir imagen Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest', '.']
  
  # Paso 2: Subir imagen a Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest']
  
  # Paso 3: Desplegar en GKE (opcional - solo si el cluster existe)
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/microservicio-simple'
      - 'microservicio-simple=gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=${_REGION}-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=microservicio-cluster'

substitutions:
  _SERVICE_NAME: 'microservicio-simple'
  _REGION: 'us-central1'

images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'

timeout: '1800s'
